import numpy as np
import pickle

with open("out.bin", "rb") as f:
    drawing = pickle.load(f)


def gcode(code, comment = "", **args):
    '''print code followd by kwargs'''
    arg_list = []
    for arg, value in args.items():
        arg_list.append(f"{arg}{value:.5g}")
    return f'{code} {" ".join(arg_list)}; ({comment})\n'


SCALE_FACTOR = 150
XY_OFFSET = np.array([20,20])
G_CODE_FILE = "outputs/{color_name}_strokes.gcode"
PD_COMMAND = gcode("M300", comment="pen down",S=90) + gcode("G4", P=100, comment = "wait")
PU_COMMAND = gcode("M300", comment="pen up", S=160) + gcode("G4", P=100, comment = "wait")
FEEDRATE = 500
HEADER = '''(The Follwoing gcode was generated by the line_painter program)


'''



for color_name, line_set in drawing.items():
    #print how many distinct lines each color has
    print(color_name, "has", len(line_set), "lines")
    if len(line_set) == 0:
        continue
    with open(G_CODE_FILE.format(color_name = color_name[1:]), "w") as f:
        f.write(HEADER)
        f.write(f"(This will use pen {color_name})\n\n")
        f.write(gcode("G1", F=FEEDRATE, comment="global feedrate"))
        for line in line_set:
            line *= SCALE_FACTOR
            line += XY_OFFSET
            f.write(gcode("G0", X=line[0,0], Y=line[0,1]))
            f.write(PD_COMMAND)
            for point in line[1:]:
                f.write(gcode("G1", X=point[0], Y=point[1]))
            f.write(PU_COMMAND)
        f.write(gcode("G0", X=0, Y=0))







print("done")